### PR TITLE
Adding self to contributors

### PR DESCRIPTION
**Pull request by collinmast**
Adding self to contributors to start contributing to the uribeacon project

### CODE REVIEW

**Comment by collinmast** [comment]
Hello,

My company, KS Technologies, signed a corporate CLA so that we can make contributions

**Comment by schilit** [comment]
Thanks!

**Comment by schilit** [comment]
I understand you have the corporate CLA but the system checks based on github user ids.

Would you mind also signing the cla on this link: https://cla.developers.google.com/clas

Thanks

**Comment by schilit** [comment]
Colin,

My mistake, CLA checking should be automated based on all members of your organization that are part of a google group. Did you follow the process below? If so what is the name of your google group?

Bill

----
Please email these contributors and ask them to forward this message to their legal departments:

Hello,

Thank you for contributing to Google open source projects. We deeply appreciate your contributions.

We are transitioning to a new automated system for CLA management. Please create a google group (https://groups.google.com/) and make yourself and one other employee of your company an owner. Once this is done, please email the name of this group and a pdf of your signed CLA to cla-submissions@google.com.

Add the emails of your authorized contributors to this group and they will automatically be authorized to contribute to Google projects. Remove them from the group and their authorization will be withdrawn. The owners of this group will soon be able to edit contact information directly in Q1 2015.

If you could please fill out this template with your information we’ll link it to your google group and you’ll be all set. 

List name: yourlist@googlegroups.com
name: 'Company Name'
contact_info: <
  address: '121 Jump Street, Mountain View, CA 94949'
  email: 'email@domain.tld'
  country: 'United States'
  phone: '+1 555-555-5555'
  contact_name: 'Name Lastname <email@domain.tld>'
  contact_title: 'Corporate point of contact'
>

Please email cla-submissions@google.com if you experience any issues. Thank you for your patience and we hope to see many more contributions from you in the future.

**Comment by dinhviethoa** [comment]
Also, could you add your name to CONTRIBUTORS along with a first contribution?
Thanks!

**Comment by schilit** [comment]
Hi @collinmast Colin,

Let me know when you get indication that the corporate CLA is setup. Currently the system hasn't approved but it might be stuck.

Bill

**Comment by collinmast** [comment]
@schilit Bill,

We resubmitted our corporate CLA and I signed a personal one as well. We are still awaiting a response for our corporate one that was submitted. Just wanted to touch base on the status.

Collin

**Comment by collinmast** [comment]
Corporate CLA was approved, and now the pull request looks like it will merge without any issues.

**Comment by collinmast** [comment]
@schilit Bill,
We received verification of our corporate CLA. Our commit is adding team members to the contributors list. I verified that all the commit authors are ready to contribute

**Pull request merged**
