### PR TITLE
Dialog for when there are multiple UriBeacons

### PR DESCRIPTION
**Pull request by g-ortuno**
device-2015-01-30-105520

### CODE REVIEW

**Comment by schilit** [comment]
How about the name, so I would see: UriBeacon Config m (C6:A0:9A:51:00:FF)

**Comment by g-ortuno** [comment]
I thought about that. But if you're a manufacturer all your beacons are
probably named the same...

**Comment by schilit** [comment]
Actually when we are developing beacons we are setting the name field to something understandable... roy has been using "UriBeacon Config bg" and I've been using "mUriBeacon Config" for mbed.

It is only after you debug your beacon that you give it a universal name like "UriBeacon Config"

**Comment by g-ortuno** [comment]
Redesign of the dialog window
beacon_chooser

**Comment by schilit** [comment]
Beautiful!

**Pull request merged**
