### PR TITLE
Update test

### PR DESCRIPTION
**Pull request by schilit**
@g-ortuno Maven at mockito.org is no longer publishing version 1.10.14. Update.

### CODE REVIEW

**Comment by schilit** [comment]
Android Studio doesn't show 1.10.19, in the add library dialog -- only the beta version. And when I add 1.10.19 directly into the gradle file it doesn't build -- probably because it can't download it. So something is broken between maven at org.mockito and gradle in Android studio.

**Comment by schilit** [comment]
But see what Travis says before merging

**Comment by g-ortuno** [comment]
I think travis is frozen today. I've been waiting on a Physical Web PR for two hours now.

**Comment by schilit** [comment]
That is sad. I'm OK waiting until tomorrow morning since Roy is still testing the apk.

**Pull request merged**
